{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cluster.fullname" . }}
  labels:
    application: spilo
    spilo-cluster: {{ include "postgres-cluster.fullname" . }}
type: Opaque
data:
  superuser-password: {{ .Values.secret.superuser | default "" | b64enc | quote }}
  replication-password: {{ .Values.secret.replication | default "" | b64enc | quote }}
  admin-password: {{ .Values.secret.admin | default "" | b64enc | quote }}
{{- end -}}